19 core refactoring
lsd-maddrive/adas_system pull request #24
Opened 2022-05-28 12:12 UTC by GeneralFire

Минимально рабочая имплементация детектора и классификатора
Рефактор ноутбуков для обучения энкодера и получения метрик
Поддержка модели в json-формате

2022-05-28 16:56 UTC, GeneralFire commented
TODO:
fix detector: return relative sign position, not cropped images
fix classifier: pass whole image with relative position of signs

2022-05-28 19:31 UTC, KaiL4eK requested changes
- Кажется, что папка src/models/hub - лишняя для пакета? Может, ее оставить в рамках кода для обучения?
- Папка src/aws тоже кажется избыточной. В пакете maddrive надо оставить только самое необходимое, а остальное вынести, так как этот пакет будет устанавливаться в другие проекты.
-  Соответственно, может таким образом папка src и уйдет и останется только подмодуль `sign_det` с необходимыми функциями. Если есть что-то, то можно явно создать папочку utils, но src внутри sign_det выглядит как еще одна вложенность глобальных исходников.

В целом все отлично, нужно поменять структуру, совладать с poetry (и еще в Dev пакеты добавить opencv-python) и все будет шик!

2022-05-28 19:31 UTC, KaiL4eK commented on .vscode/settings.json
> +{
Вот это и папку надо удалить из репо

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/utils/fs.py
> -import cv2
Надо вернуть - это utils общий для всех задач adas

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/classifier.py
> +def test():
Тест и данные перенести в папку tests в корне и реализовать в виде функций-тестов. Загрузку данных сделать в виде фикстур

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +def test():
этот пример можно сделать в виде  примера в папке examples, которая загружает (import) нужные модули и делает предсказание

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +        path_to_yolo_cfg=path_prefix + 'yolov5L_custom_anchors.yaml',
Конфиг засунуть внутрь модели

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +        path_to_model_config='encoder_config.json'
Конфиг внутрь модели

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +        path_to_centroid_location='centroid_location.txt',
Центроиды по-умолчанию внутрь модели, но дать возможность задать свои центроиды. Таким образом можно из выборки убрать классы или добавить свои классы. Предлагаю txt заменить на формат json, чтобы удобнее было читать и редактировать.

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +    model = YoloSignsDetector()
Класс полноценного детектора можно сделать в виде объединяющего класса, которы принимает на вход инициализированные детектор и классификатор вместо инициализации внутри.

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +    img = imread_rgb('../../tests/test_data/custom_test.png')
Пути заменить на пути относительно корня проекта. Внутри пакета никто не должен использовать пути. Все пути должны быть заданы при конструировании объектов в исполняемом скрипте.

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolo_detector.py
> +    img = imread_rgb('../../tests/test_data/custom_test.png')
Использовать os.path.*

2022-05-28 19:31 UTC, KaiL4eK commented on maddrive_adas/sign_det/yolov5l_custom_anchors.yaml
> +# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
Эти конфиги по идее не нужны в исходниках - они будут в файле модели или останутся в коде обучения

2022-05-28 19:33 UTC, KaiL4eK reviewed
Еще, в качестве возврата от detection стадии нужно на каждую картинку возвращать:
list[dict], где dict - это каждый объект. Можно вместо dict сделать класс с соответствующими атрибутами. А классификатор, например, будет обогащать эти объекты доп. инфой.

2022-06-12 15:39 UTC, GeneralFire commented on maddrive_adas/sign_det/yolo_detector.py
> +        path_to_yolo_cfg=path_prefix + 'yolov5L_custom_anchors.yaml',
done, на вики страничка с словарями, каждый класс проверяет наличие необходимых ключей

2022-06-15 17:21 UTC, GeneralFire commented on maddrive_adas/sign_det/yolo_detector.py
> +    model = YoloSignsDetector()
Done

2022-06-15 17:47 UTC, GeneralFire commented on maddrive_adas/utils/fs.py
> -import cv2
Вернул в src в maddrive

2022-06-18 22:44 UTC, KaiL4eK requested changes
Выглядит намного лучше, остались мелкие правки и готов завтра слить)

2022-06-18 22:44 UTC, KaiL4eK commented on pyproject.toml
> -python = ">=3.8,<3.11"
Восстановить lock файл

2022-06-18 22:44 UTC, KaiL4eK commented on pyproject.toml
> -opencv-python-headless = "^4.5.5"
headless дб в core зависимостях, а opencv-python можно в dev

2022-06-18 22:44 UTC, KaiL4eK commented on pyproject.toml
> -python = ">=3.8,<3.11"
Poetry

2022-06-18 22:44 UTC, KaiL4eK commented on Untitled.ipynb
> +{
Он точно нужен? Мб как-то обозвать и в какие-нибудь примеры?

2022-06-18 22:44 UTC, KaiL4eK commented on .flake8
> +    E402
Это сложно соблюсти? Хорошая практика все наверху держать

2022-06-18 22:44 UTC, KaiL4eK commented on example/manual_test.py
> +    sign = d.detect_batch([img1, img2])
Возвращает один знак? (По названию переменной)

2022-06-18 22:44 UTC, KaiL4eK commented on example/manual_test.py
> +    # TODO: fix unexpected behaviour
Что за поведение,  которого не ждут?)

2022-06-18 22:44 UTC, KaiL4eK commented on maddrive_adas/__init__.py
> +from .utils import *
Это здесь разве нужно?

2022-06-19 11:52 UTC, GeneralFire commented on .flake8
> +    E402
нужно было для sys.path.append, исправил

2022-06-19 12:29 UTC, KaiL4eK approved these changes

2022-06-19 12:33 UTC, merged