35 support winter season detection and classification
lsd-maddrive/adas_system pull request #37
Opened 2023-01-08 17:54 UTC by GeneralFire

Добавление аугментации, имитирующей перекрытие объекта

2023-01-09 21:51 UTC, GeneralFire commented
Добавлено обучение с новой аугментацией
некоторые ноутбуки перенесены в скрипты
**обновлены тесты!!!!!!!!!!!!!!!!** плз, проверь их, мне не нравится то, как они выглядят
выпелены доки, так как ни разу не пользовался, бесполезно, ссылки на них есть/были в readme
добавлен адекватый класс checkpoint, для загрузки моделек как для обучения, так и для использования

2023-02-28 21:04 UTC, KaiL4eK requested changes

2023-02-28 21:04 UTC, KaiL4eK commented on tests/test_checkpoint.py
> +from typing import Tuple
Я бы в тесты добавил проверок, что загруженный чекпоинт (модель) отдает результат в ожидаемом формате (формат dict, нужные ключи и т.д.). В этих тестах есть проверки загрузки/сохранения, но важнее проверить, как сама модель работает

2023-02-28 21:04 UTC, KaiL4eK commented on SignDetectorAndClassifier/notebooks/README.md
>  * **1_0_ClassifierResearch** - классификатор для распознования знаков. Изначально ноутбук планировался для обучения на RTSD, но в ходе работы был признан неактуальным. `Не предполагает использование.
Я бы предложил сделать папки notebooks и в ней сделать SignDetectorAndClassifier. У нас области работы будут еще в сегментации, алгоритмике, а тут получается, что на каждую тему надо будет папку. Лучше notebooks, docs и внутри дробить по темам

2023-02-28 21:04 UTC, KaiL4eK commented on download_models.py
>  _encoder_url: str = \
может это в scripts?

2023-02-28 21:04 UTC, KaiL4eK commented on example/manual_test.py
> -from typing import List
Почему удалены? Подобные проверки перенесены в тесты? Если нет, то можно перенести, главное, чтобы была хоть какая-нибудь возможность проверить код и поотлаживать

2023-02-28 21:04 UTC, KaiL4eK commented on maddrive_adas/utils/env.py
> +    assert 'VIRTUAL_ENV' in os.environ, f'Run {__file__} in venv to resolve project root'
Обычно от __file__ берется несколько раз .parent, так как __file__ в файле фиксирован и можно явно следовать структуре проекта

2023-02-28 21:04 UTC, KaiL4eK commented on maddrive_adas/utils/general.py
>  LOGGER = set_logging(
Логер не должен настраиваться в исходниках. Только в скриптах или тестах (редко)

2023-02-28 21:04 UTC, KaiL4eK commented on maddrive_adas/utils/general.py
>  LOGGER = set_logging(
Либо сделай функцию получения логера с lazy настройкой, но один объект логера хрнаить плохо, так как у каждого логера дб свои имена

2024-03-26 19:34 UTC, merged